version: '3.8'

services:
  frontend:
    image: unclechuen/orcas-frontend:latest
    ports:
      - "80:3000"
    restart: always
  
  backend:
    image: unclechuen/orcas-backend:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SERVER_URL=jdbc:mysql://db:3306
      - SERVER_USERNAME=root
      - SERVER_PASSWORD=root

  db:
    image: mysql
    restart: always
    volumes:
      - ./:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
